//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prmToolkit.NotificationPattern.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prmToolkit.NotificationPattern.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não deve ser igual a {1}..
        /// </summary>
        public static string IfAreEquals {
            get {
                return ResourceManager.GetString("IfAreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ter uma instância para uma coleção..
        /// </summary>
        public static string IfCollectionIsNull {
            get {
                return ResourceManager.GetString("IfCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma coleção com pelo menos um item dentro.
        /// </summary>
        public static string IfCollectionIsNullOrEmpty {
            get {
                return ResourceManager.GetString("IfCollectionIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não deve conter {1}..
        /// </summary>
        public static string IfContains {
            get {
                return ResourceManager.GetString("IfContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não deve ser igual a zero..
        /// </summary>
        public static string IfEqualsZero {
            get {
                return ResourceManager.GetString("IfEqualsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser verdadeiro..
        /// </summary>
        public static string IfFalse {
            get {
                return ResourceManager.GetString("IfFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser menor que {1}..
        /// </summary>
        public static string IfGreaterOrEqualsThan {
            get {
                return ResourceManager.GetString("IfGreaterOrEqualsThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser menor ou igual a {1}..
        /// </summary>
        public static string IfGreaterThan {
            get {
                return ResourceManager.GetString("IfGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ter seu comprimento menor ou igual a {1} caracter(es)..
        /// </summary>
        public static string IfLengthGreaterThan {
            get {
                return ResourceManager.GetString("IfLengthGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ter seu comprimento maior ou igual a {1} caracter(es)..
        /// </summary>
        public static string IfLengthLowerThan {
            get {
                return ResourceManager.GetString("IfLengthLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ter exatamente {1} caracter(es)..
        /// </summary>
        public static string IfLengthNoEqual {
            get {
                return ResourceManager.GetString("IfLengthNoEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior que {1}..
        /// </summary>
        public static string IfLowerOrEqualsThan {
            get {
                return ResourceManager.GetString("IfLowerOrEqualsThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior ou igual a {1}..
        /// </summary>
        public static string IfLowerThen {
            get {
                return ResourceManager.GetString("IfLowerThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser igual a {1}..
        /// </summary>
        public static string IfNotAreEquals {
            get {
                return ResourceManager.GetString("IfNotAreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um Cnpj válido..
        /// </summary>
        public static string IfNotCnpj {
            get {
                return ResourceManager.GetString("IfNotCnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve conter {1}..
        /// </summary>
        public static string IfNotContains {
            get {
                return ResourceManager.GetString("IfNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um Cpf válido..
        /// </summary>
        public static string IfNotCpf {
            get {
                return ResourceManager.GetString("IfNotCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma data válida..
        /// </summary>
        public static string IfNotDate {
            get {
                return ResourceManager.GetString("IfNotDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um endereço de e-mail válido..
        /// </summary>
        public static string IfNotEmail {
            get {
                return ResourceManager.GetString("IfNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um Guid válido..
        /// </summary>
        public static string IfNotGuid {
            get {
                return ResourceManager.GetString("IfNotGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser igual a nulo..
        /// </summary>
        public static string IfNotNull {
            get {
                return ResourceManager.GetString("IfNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser nulo..
        /// </summary>
        public static string IfNotNullOrEmpty {
            get {
                return ResourceManager.GetString("IfNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve estar no intervalo de {1} a {2}..
        /// </summary>
        public static string IfNotRange {
            get {
                return ResourceManager.GetString("IfNotRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma URL válida..
        /// </summary>
        public static string IfNotUrl {
            get {
                return ResourceManager.GetString("IfNotUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não deve ser igual a nulo..
        /// </summary>
        public static string IfNull {
            get {
                return ResourceManager.GetString("IfNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório..
        /// </summary>
        public static string IfNullOrEmpty {
            get {
                return ResourceManager.GetString("IfNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório com tamanho mínimo de {1} caracter(es) e máximo {2} caracter(es)..
        /// </summary>
        public static string IfNullOrInvalidLength {
            get {
                return ResourceManager.GetString("IfNullOrInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório..
        /// </summary>
        public static string IfNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("IfNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não deve estar no intervalo de {1} a {2}..
        /// </summary>
        public static string IfRange {
            get {
                return ResourceManager.GetString("IfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser falso..
        /// </summary>
        public static string IfTrue {
            get {
                return ResourceManager.GetString("IfTrue", resourceCulture);
            }
        }
    }
}
