//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prmToolkit.NotificationPattern.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prmToolkit.NotificationPattern.Resources.Message", typeof(Message).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não deve ser igual a {1}..
        /// </summary>
        public static string IfAreEquals {
            get {
                return ResourceManager.GetString("IfAreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter uma instância para uma coleção..
        /// </summary>
        public static string IfCollectionIsNull {
            get {
                return ResourceManager.GetString("IfCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser uma coleção com pelo menos um item dentro.
        /// </summary>
        public static string IfCollectionIsNullOrEmpty {
            get {
                return ResourceManager.GetString("IfCollectionIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não deve conter {1}..
        /// </summary>
        public static string IfContains {
            get {
                return ResourceManager.GetString("IfContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é inválido..
        /// </summary>
        public static string IfEnumInvalid {
            get {
                return ResourceManager.GetString("IfEnumInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não deve ser igual a zero..
        /// </summary>
        public static string IfEqualsZero {
            get {
                return ResourceManager.GetString("IfEqualsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser verdadeiro..
        /// </summary>
        public static string IfFalse {
            get {
                return ResourceManager.GetString("IfFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser menor que {1}..
        /// </summary>
        public static string IfGreaterOrEqualsThan {
            get {
                return ResourceManager.GetString("IfGreaterOrEqualsThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser menor ou igual a {1}..
        /// </summary>
        public static string IfGreaterThan {
            get {
                return ResourceManager.GetString("IfGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter seu comprimento menor ou igual a {1} caracter(es)..
        /// </summary>
        public static string IfLengthGreaterThan {
            get {
                return ResourceManager.GetString("IfLengthGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter seu comprimento maior ou igual a {1} caracter(es)..
        /// </summary>
        public static string IfLengthLowerThan {
            get {
                return ResourceManager.GetString("IfLengthLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter exatamente {1} caracter(es)..
        /// </summary>
        public static string IfLengthNoEqual {
            get {
                return ResourceManager.GetString("IfLengthNoEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser maior que {1}..
        /// </summary>
        public static string IfLowerOrEqualsThan {
            get {
                return ResourceManager.GetString("IfLowerOrEqualsThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser maior ou igual a {1}..
        /// </summary>
        public static string IfLowerThan {
            get {
                return ResourceManager.GetString("IfLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser igual a {1}..
        /// </summary>
        public static string IfNotAreEquals {
            get {
                return ResourceManager.GetString("IfNotAreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser um Cnpj válido..
        /// </summary>
        public static string IfNotCnpj {
            get {
                return ResourceManager.GetString("IfNotCnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve conter {1}..
        /// </summary>
        public static string IfNotContains {
            get {
                return ResourceManager.GetString("IfNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser um Cpf válido..
        /// </summary>
        public static string IfNotCpf {
            get {
                return ResourceManager.GetString("IfNotCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser uma data válida..
        /// </summary>
        public static string IfNotDate {
            get {
                return ResourceManager.GetString("IfNotDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser um endereço de e-mail válido..
        /// </summary>
        public static string IfNotEmail {
            get {
                return ResourceManager.GetString("IfNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser um Guid válido..
        /// </summary>
        public static string IfNotGuid {
            get {
                return ResourceManager.GetString("IfNotGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser igual a nulo..
        /// </summary>
        public static string IfNotNull {
            get {
                return ResourceManager.GetString("IfNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser nulo..
        /// </summary>
        public static string IfNotNullOrEmpty {
            get {
                return ResourceManager.GetString("IfNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve estar no intervalo de {1} a {2}..
        /// </summary>
        public static string IfNotRange {
            get {
                return ResourceManager.GetString("IfNotRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser uma URL válida..
        /// </summary>
        public static string IfNotUrl {
            get {
                return ResourceManager.GetString("IfNotUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não deve ser igual a nulo..
        /// </summary>
        public static string IfNull {
            get {
                return ResourceManager.GetString("IfNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string IfNullOrEmpty {
            get {
                return ResourceManager.GetString("IfNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório e deve conter entre {1} e {2} caracteres..
        /// </summary>
        public static string IfNullOrInvalidLength {
            get {
                return ResourceManager.GetString("IfNullOrInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string IfNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("IfNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não deve estar no intervalo de {1} a {2}..
        /// </summary>
        public static string IfRange {
            get {
                return ResourceManager.GetString("IfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser falso..
        /// </summary>
        public static string IfTrue {
            get {
                return ResourceManager.GetString("IfTrue", resourceCulture);
            }
        }
    }
}
